import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import ts from "typescript";
import {createRequire} from "node:module";
import {PDFDocument} from "pdf-lib";
import JSZip from "jszip";
const require=createRequire(import.meta.url);
function load(file){const exports={};new Function("exports","require","Buffer",ts.transpileModule(fs.readFileSync(file,"utf8"),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText)(exports,require,Buffer);return exports;}
const {renderCommercial,documentLines}=load("lib/commercial/render.ts");
const {billingSchema}=load("lib/commercial/billing.ts");
const sample={reference:"TEST-001",kind:"contrato",title:"Análise estatística de pesquisa — demonstração",body:"Condições ajustadas entre as partes.\nTrês fases: organização, análise e relatório.",created:"19/09/2026",client:{legal_name:"Cliente de Teste",tax_id:"12345678901",email:"teste@example.test",phone:"44999998888",address:"Rua de Teste, 10",city:"Maringá",state:"PR",postal_code:"87000000",institution:"Instituição de Teste",representative:""},provider:{provider_name:"HAS Analytics — Exemplo",provider_tax_id:"12345678901",provider_address:"Endereço demonstrativo",provider_contact:"teste@example.test"},budget:{number:"ORC-TESTE",description:"Análise e interpretação de dados experimentais.",notes:"Entrega após recebimento do banco e confirmação das condições acordadas.",subtotal:810,discount:10,total:729,payment:"Pix: 50% no início e 50% na entrega",due:"2026-10-20",validity:"2026-09-30"},items:[{description:"Organização do banco",quantity:1,unit_price:250},{description:"Análise estatística",quantity:8,unit_price:70},{description:"Relatório e interpretação",quantity:1,unit_price:0}]};
test('billing rejects incomplete legal identity and keeps Brazilian accented text',()=>{assert.equal(billingSchema.safeParse(sample.client).success,true);assert.equal(billingSchema.safeParse({...sample.client,tax_id:'123'}).success,false);assert.equal(billingSchema.safeParse({...sample.client,address:''}).success,false)});
test('PDF and genuine DOCX contain one consistent version and agreed amounts',async()=>{const files=await renderCommercial(sample);assert.equal(files.pdf.subarray(0,5).toString(),'%PDF-');const pdf=await PDFDocument.load(files.pdf);assert.ok(pdf.getPageCount()>=1);const zip=await JSZip.loadAsync(files.word);const xml=await zip.file('word/document.xml').async('string');assert.match(xml,/Cliente de Teste/);assert.match(xml,/TEST-001/);assert.match(xml,/729,00/);assert.match(xml,/Três fases/);assert.ok(documentLines(sample).join(' ').includes('50%'));if(process.env.QA_ARTIFACTS){fs.mkdirSync('../commercial-qa',{recursive:true});fs.writeFileSync('../commercial-qa/sample.pdf',files.pdf);fs.writeFileSync('../commercial-qa/sample.docx',files.word);}});
test('long conditions paginate and unsupported glyphs fail instead of silently changing text',async()=>{const files=await renderCommercial({...sample,body:'Cláusula de teste com texto extenso. '.repeat(700)});assert.ok((await PDFDocument.load(files.pdf)).getPageCount()>3);await assert.rejects(()=>renderCommercial({...sample,body:'Emoji 😀'}),/caractere/)});

function actions(role='client',signed=true){let storageCalls=0;const imports={"zod":require('zod'),"node:crypto":require('node:crypto'),"pdf-lib":require('pdf-lib'),"@/lib/commercial/render":{renderCommercial},"@/lib/commercial/billing":{billingSchema},"@/lib/supabase/server":{createClient:async()=>({auth:{getUser:async()=>({data:{user:signed?{id:'11111111-1111-4111-8111-111111111111'}:null}})},from:table=>({select:()=>({eq:()=>({single:async()=>({data:table==='profiles'?{role}:null,error:null})})})}),storage:{from:()=>{storageCalls++;throw Error('Storage must not be reached');}}})}};const exports={};new Function('exports','require',ts.transpileModule(fs.readFileSync('app/admin/commercial-actions.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText)(exports,id=>imports[id]);return {exports,calls:()=>storageCalls};}
test('server denies client Word access before touching storage',async()=>{const a=actions();await assert.rejects(()=>a.exports.commercialDownload('30000000-0000-4000-8000-000000000001','word'),/exclusivo/);assert.equal(a.calls(),0)});
test('server prevents non-admin document generation and unauthenticated downloads',async()=>{const a=actions();const result=await a.exports.generateCommercialDocument(new FormData());assert.equal(result.success,false);assert.match(result.message,/restrito/);assert.equal(a.calls(),0);await assert.rejects(()=>actions('client',false).exports.commercialDownload('30000000-0000-4000-8000-000000000001','pdf'),/Entre novamente/)});
test('publication requires an explicit review confirmation',async()=>{const a=actions('admin');const result=await a.exports.publishCommercial('30000000-0000-4000-8000-000000000001',false);assert.equal(result.success,false);assert.match(result.message,/confirme/);assert.equal(a.calls(),0)});
